### ISSUE TITLE
[Documentation] Explain what the compatibility table means

### ISSUE THREAD

**Issue by jcalcaben** [magento-research/pwa-studio#1054]
Add content to the Magento compatibility table page explaining what it means for PWA Studio to be compatible with a certain version of Magento.

**Comment by supernova-at** [comment]
Since I worked on the `validate-queries` build step I can speak to that:

Run as part of `yarn build`, the `validate-queries` script will:
1. Issue a [GraphQL introspection query](https://graphql.org/learn/introspection/) to the endpoint specified in `MAGENTO_BACKEND_URL` in `.env`
1. Save the resulting schema in `lastCachedGraphQLSchema.json`
1. Validate all [Apollo and literal](https://github.com/magento-research/pwa-studio/blob/develop/packages/venia-concept/.graphqlconfig#L10) GraphQL queries it finds in files ending with [.js, .graphql, or .gql](https://github.com/magento-research/pwa-studio/blob/develop/packages/venia-concept/.graphqlconfig#L11) against that schema
1. Report the results

Practically speaking, what that means is that the build will fail when the project (Venia) will issue GraphQL queries that we know the backend (Magento 2)'s schema can't handle. This was preferred over silently failing and having unreliable UI when incompatibilities arose.

Since we update Venia's GraphQL queries with each release of Magento 2 to ensure compatibility between the two, the compatibility table was born to document which versions of PWA (Venia) are compatible with which versions of Magento 2:

When PWA Studio `2.0.0` was released, all GraphQL queries were compatible with Magento `2.3.0`.
When PWA Studio `2.1.0` was released, all GraphQL queries were compatible with Magento `2.3.1`.

This list will surely grow over time.

Currently, incompatibilities can arise (and the build will fail) in the following scenarios:
* A developer has the latest PWA Studio (`>2.0.0`), but his/her `MAGENTO_BACKEND_URL` still points to a Magento 2 instance running `2.3.0`
*  A developer is running an older version of PWA Studio (`2.0.0`), but has updated his/her Magento 2 backend to `2.3.1`, and points to it with `MAGENTO_BACKEND_URL`

The scenarios above also illustrate how a developer could solve incompatibility issues:
* Upgrade or downgrade his/her version of PWA Studio OR
* Upgrade or downgrade his/her version of Magento 2
