### ISSUE TITLE
[doc]: How to integrate social Auth

### ISSUE THREAD

**Issue by bkmagnetron** [magento-research/pwa-studio#1128]
Different options available to implement social auth(signup and signin) in Venia storefront setup documentation would be more helpful.

**Comment by bkmagnetron** [comment]
@jcalcaben 
Some kind of direction would be useful. We have been stumbling to launch a E-Commerce with Headless Magento for a long time now.
We started with less Magento knowledge. We thought the Standard Magento theme implementation won't be helpful with Native Mobile app. So, we decided to have both the web and mobile app as headless. That's why we came to try PWA Studio assuming that we can have the same architecture for both the mobile and web.

We seemed to be blocked with questions where no one has the answer.
How do we integrate Single Sign-on in PWA Studio?
Do the existing plugins in Magento Marketplace works with PWA Studio?
We really need SEO but not sure whether it supported in PWA Studio or not?

**Comment by awilcoxa** [comment]
Needs a more comprehensive approach/response from architecture. Will move forward for team grooming.

**Comment by supernova-at** [comment]
> How do we integrate Single Sign-on in PWA Studio (like Keycloak, Social Auth, etc.,)?

This is what needs a more comprehensive approach from architecture. We'll get this prioritized.

> Do the existing plugins in Magento Marketplace works with PWA Studio?

Since your PWA will take over as your front end, all backend plugins will work and front end plugins will not.

> We really need SEO but not sure whether it supported in PWA Studio or not?

There are some SEO benefits currently but the big missing piece is server side rendering (SSR). We're also currently in design on this.

> Can we even use the PWA Studio in production?

Yep!  There are already a handful of PWA Studio PWAs in production (ex: https://www.ukmeds.co.uk/)

**Comment by awilcoxa** [comment]
Social Auth is currently out of scope for PWA Studio. Closing but will re-open in future as needed.
