### ISSUE TITLE
[bug]: Venia PDP form fields have wrong labels and Size labels are not in ascending order

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1181]
Steps - 
1. Navigate to any PDP on Venia store front example - https://veniapwa.com/aurora-sleeveless-blouse.html
2. Observe the Fashion Color and Fashion Size options.

Expected -  Fashion Color name should match the mock color and Fashion size should be in Ascending order.
Actual - Fashion Color name does NOT match the mock color and Fashion size are NOT in Ascending order.

**Comment by johnhughes1984** [comment]
I don't believe either of these issues require a fix within Venia at present.

Breaking this down into 2 issues:

1.  'Fashion Color name should match the mock color'

The reason the color label doesn't match the actual color output on the page is because the colors are actually being randomised because the values (i.e. hexadecimal codes) are not currently available from the GraphQL endpoint.  I don't see any benefit in changing the labels (which are populated correctly from the GraphQL data) to match the mock colors.  Surely it's better to wait until the GraphQL implementation has been completed so that the correct colors can be populated.

> See: https://github.com/magento-research/pwa-studio/blob/develop/packages/venia-concept/src/components/ProductOptions/swatch.js#L58 for the current marked TODO around GraphQL data missing

2. 'Fashion size should be in Ascending order'

The order of attribute options should be controlled by the merchant in the Magento admin panel.  Ordering them within Venia would break this control.  As you can see in the first 2 screenshots below the order of the option values against the product matches the order.  The only final verification that should be made here is that the GraphQL endpoint is actually ordering by the order the admin user sets rather than the ID value of the attribute option - I note this because querying the attribute option data for the product linked above the attribute option values are all in order of their `value_index` (see 3rd and final screenshot below) so it is unclear what is powering the order.  However, this is a GraphQL concern, not a PWA Studio / Venia one.

<img width="1440" alt="Screenshot 2019-06-18 at 12 13 06" src="https://user-images.githubusercontent.com/3949917/59677722-768ac680-91c2-11e9-9d7a-f962a94a095f.png">

<img width="1440" alt="Screenshot 2019-06-18 at 12 14 00" src="https://user-images.githubusercontent.com/3949917/59677786-96ba8580-91c2-11e9-9038-633b4e3c32b4.png">

<img width="1440" alt="Screenshot 2019-06-18 at 12 15 09" src="https://user-images.githubusercontent.com/3949917/59677958-15172780-91c3-11e9-8b01-f891a1cc0e94.png">

**Comment by supernova-at** [comment]
Thanks for the great write up @johnhughes1984 !

Closing as not a valid issue.
