### ISSUE TITLE
[bug]: Hitting Enter key of keyboard on empty search field returns "Undefined" text in search field

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1209]
Steps - 
1. Navigate to Venia store front and click on Search icon.
2. Click in search text field and hit Enter key of keyboard without entering any search input.

Expected - Nothing should happen.
Actual - search submitted!,  results says no results found and search field shows undefined text.

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/b9f74e30-a943-41fa-90a4-af64802abfa8)

**Comment by awilcoxa** [comment]
Replicated, does appear that we don't have a the case built for "null" search (or rather that the search should simply not submit if null). Moving to for grooming. @soumya-ashok would be great to get yoru input here?

**Comment by soumya-ashok** [comment]
@awilcoxa Yes, this is on my list to discuss with the team today.

**Comment by soumya-ashok** [comment]
@dpatil-magento 
On desktop, if the user hits the return key with the cursor in the search field and no text entered, there is no change to the page.

On mobile, since tapping the search field will pull up the keyboard, if the user taps return in the search field without typing anything, the keyboard stays in place and there is no change to the page.

**Comment by jflanaganuk** [comment]
#mmuk2019

**Comment by supernova-at** [comment]
Related PR #1363.
