### ISSUE TITLE
[bug]: [RE-Opened ] - Second search icon breaks header bar during load

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#1273]
**Describe the bug**
For a few milliseconds during load, this happens:

![doubled mag](https://user-images.githubusercontent.com/1643758/58389898-e5299980-7ff3-11e9-9766-e72c80351620.png)

And then it's back to this:

![single mag](https://user-images.githubusercontent.com/1643758/58389920-038f9500-7ff4-11e9-9af3-a3e0067e6e3e.png)

**To Reproduce**
1. Completely clear cache and launch incognito mode.
2. Start a dev server.
3. Use the Chrome dev tools mobile emulator to artificially limit network and CPU speed.
4. Load some page.

**Expected behavior**
No jank from header.

**Possible solutions**
It's probably something small.

**Please complete the following device information:**
 - iPhone SE and Nokia 2
 - iOS and Android
 - Safari and Chrome
 - PWA Studio Version: 2.1.0

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by dpatil-magento** [comment]
Issue still exists on search page. example: https://develop.pwa-venia.com/search.html?query=top

**Comment by tjwiebell** [comment]
@dpatil-magento - Opposed to the original bug, this behavior does seem intentional. We're using a React feature called Suspense that automatically handles rendering a fallback placeholder (most typically a loading indicator), but in this instance, we're rendering a search icon until the SearchBar component is loaded.

This may not be the preferred experience, so lets loop in @soumya-ashok, and see if there's a UX change we can make to improve this slow network experience. Soumya, here is what's rendered while `SearchBar` is being loaded on a slow network; I'll definitely fix the padding, but is there a different icon or loading indicator we'd like to show here?

![Screen Shot 2019-06-11 at 11.52.00 AM.png](https://images.zenhubusercontent.com/5c06f0217b12772835644648/3301bcf5-59bc-4309-8b8d-1935cf0586d3)

**Comment by soumya-ashok** [comment]
@tjwiebell The original intent is that when the search icon is tapped, the field appears, like in the linked screen
https://magento.invisionapp.com/share/PXRVAKRE9GH
The design needs improvement to begin with, and I haven't addressed that yet. For slow connections, I need to understand what is possible and what isn't in this case, based on the original design. Could we discuss?

**Comment by soumya-ashok** [comment]
@tjwiebell Mockup attached. Please let me know if this will work.

Static background that mimics a form field with a loading indicator that matches the one on the "add to cart" button. Colors adjusted for header.

![Search Loading.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/43a28d0e-5256-4f7c-85b0-5069dc66da99)
