### ISSUE TITLE
Toast blocks header on add to cart failure

### ISSUE THREAD

**Issue by soumya-ashok** [magento-research/pwa-studio#1331]
Steps to reproduce:

Tap "add to cart" on the Isadora Skirt PD page, add to cart fails and the resulting error toast completely blocks the header.

Considering the add to cart failure was a result of user action, the toast message is unspecific. It should read "Unable to add product to cart. Specify options before trying again." or similar.

![Screen Shot 2019-06-12 at 1.55.36 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/66628802-3646-456b-ae45-4cc46363b7a8)

**Comment by supernova-at** [comment]
This has been fixed on `develop`. Keeping the issue but removing the `MM19UK` label pending verification.

**Comment by sirugh** [comment]
@soumya-ashok that is the old style banner/toast.

We could convert this into a feature request to add a toast to that specific error case with that specific messaging you desire.

**Comment by soumya-ashok** [comment]
@sirugh Sure, I assume we would need to make sure this is consistent with other toasts anyway?

**Comment by sirugh** [comment]
@soumya-ashok not sure what you mean by "make sure this is consistent with other toasts". Can you clarify?

The image above shows a banner that no longer exists. That error will now appear in a toast. I am suggesting that we can wrap whatever component owns the `Add To Cart` button with an error handler that will add the toast with a more helpful message instead of the "unexpected error message"

**Comment by soumya-ashok** [comment]
@sirugh That sounds good. I was merely saying that this old error treatment would be replaced by the toasts you implemented.

**Comment by sirugh** [comment]
We should reopen/recreate an issue once we are done with the peregrine refactors to add better error messaging where appropriate. It'll need to wait until the refactors because you can only use toasts within a function component.
