### ISSUE TITLE
[bug]: Venia not rendering on iPhone 5s, iOS7

### ISSUE THREAD

**Issue by jessetaverne** [magento-research/pwa-studio#1441]
**Describe the bug**
Veniapwa.com (and our app based on venia's codebase) doesn't render on iPhone 5s, iOS7.
According to [the devdocs](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements_browsers.html) for M2.3 this should be supported

**To Reproduce**
1. Open https://veniapwa.com/ on an iPhone 5s, iOS7 (if you have a browserstack account, they have this combination)
2. Root node is stuck on "Loading Home page..."
3. Open devtools > Console
4. See errors:
```
SyntaxError: Unexpected token ','
client.js:212 SyntaxError: Use of reserved word 'class'
```

**Expected behavior**
Website loads without throwing console errors

**Screenshots**
![Screen Shot 2019-07-16 at 15 43 10](https://user-images.githubusercontent.com/4201466/61299499-80fba880-a7e0-11e9-8922-dc4680842664.png)

**Please complete the following device information:**
 - Device: iPhone 5s
 - OS: iOS 7
 - Browser: Safari
 - Browser Version: -
 - Magento Version: community 2.3.2
 - PWA Studio Version: latest
 - NPM version `npm -v`: -
 - Node Version `node -v`: -

**Please let us know what packages this bug is in regards to:**
- [x ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by awilcoxa** [comment]
iOS7 is not within current supported parameters based on market share. Closing ticket but we will update docs to reflect OS requirements

**Comment by Jordaneisenburger** [comment]
@awilcoxa I don't think this is acceptable for a PWA I quote google "And most importantly, they're web apps that work in any browser." One of the concepts behind pwa's is progressive enhancement meaning it works everywhere but gets better depending on the browser's capabilities. 

As @jessetaverne noticed there is a problem on iphone 5s, I've just now also discovered the same problem on 
- Ipad mini (IOS 9)
- IPad 5th (IOS 11)
- IPad pro 9 (IOS 11)
- IPhone 6 (IOS 11)

on IOS 11 i discovered the follow error:
![image](https://user-images.githubusercontent.com/19858728/63081822-e4ded180-bf44-11e9-9d77-057a66d6bd45.png)


 I expect that there are gonna be more devices with this problem. So i suggest we reopen this issue and take a look at the problem for all we know it could be a relative small fix that allows Studio to run on a lot more devices.

If looking into this issue doesn't seem to be worth it we need to consider showing an message for user trying to access the website using these devices.

**Comment by DanielRuf** [comment]
This is because `AbortController` is only supported by modern browsers.
See
https://developer.mozilla.org/en-US/docs/Web/API/AbortController
https://caniuse.com/#feat=abortcontroller

We have to use a polyfill:
https://github.com/search?o=desc&q=abortcontroller&s=stars&type=Repositories

For example https://github.com/mo/abortcontroller-polyfill

Generally iOS 7 is also not supported by Apple anymore. They just support the last two versions. Because the old devices use the old versions of webkit as rendering engine.

Same applies to other PWA solutions.
Most PWA features only work on modern browsers.

The device does not matter but the webkit version.
This can be easily tested with browserstack and other solutions.

```
this.controller=new AbortController
```

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError

**Comment by DanielRuf** [comment]
This is because `AbortController` is only supported by modern browsers.

```
this.controller=new AbortController
```

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError

See
https://developer.mozilla.org/en-US/docs/Web/API/AbortController
https://caniuse.com/#feat=abortcontroller

We have to use a polyfill:
https://github.com/search?o=desc&q=abortcontroller&s=stars&type=Repositories

For example https://github.com/mo/abortcontroller-polyfill

Generally iOS 7 is also not supported by Apple anymore. They just support the last two versions. Because the old devices use the old versions of webkit as rendering engine.

Same applies to other PWA solutions.
Most PWA features only work on modern browsers.

The device does not matter but the webkit version.
This can be easily tested with browserstack and other solutions.

**Comment by DanielRuf** [comment]
This is because `AbortController` is only supported by modern browsers.

```
this.controller=new AbortController
```

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError

See
https://developer.mozilla.org/en-US/docs/Web/API/AbortController
https://caniuse.com/#feat=abortcontroller

We have to use a polyfill:
https://github.com/search?o=desc&q=abortcontroller&s=stars&type=Repositories

For example one of these:
https://github.com/mo/abortcontroller-polyfill
https://github.com/mysticatea/abort-controller
https://github.com/Netflix/yetch

Generally iOS 7 is also not supported by Apple anymore. They just support the last two versions. Because the old devices use the old versions of webkit as rendering engine.

Same applies to other PWA solutions.
Most PWA features only work on modern browsers.

The device does not matter but the webkit version.
This can be easily tested with browserstack and other solutions.

**Comment by DanielRuf** [comment]
This is because `AbortController` is only supported by modern browsers.

```
this.controller=new AbortController
```

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError

See
https://developer.mozilla.org/en-US/docs/Web/API/AbortController#Browser_compatibility
https://caniuse.com/#feat=abortcontroller

We have to use a polyfill:
https://github.com/search?o=desc&q=abortcontroller&s=stars&type=Repositories

For example one of these:
https://github.com/mo/abortcontroller-polyfill
https://github.com/mysticatea/abort-controller
https://github.com/Netflix/yetch

Generally iOS 7 is also not supported by Apple anymore. They just support the last two versions. Because the old devices use the old versions of webkit as rendering engine.

Same applies to other PWA solutions.
Most PWA features only work on modern browsers.

The device does not matter but the webkit version.
This can be easily tested with browserstack and other solutions.
