### ISSUE TITLE
Review icon fonts/library for performance improvements [SPIKE]

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#376]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[X] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Continued review of Javascript size should include our use of feather-icons for Venia to ensure high performance for our reference storefront in PWA.

## Expected result:

[ ] Summary of results; recommended improvements
[ ] Creation of new issues/stories (as appropriate)

## Possible solutions:

[ ] Optimization of current library to remove unused icons (preferred)
[ ] Review of alternate icon fonts/libraries for performance

**Comment by sirugh** [comment]
Spitballing some notes/ideas/planning around this:

* FeatherIcons seems to give you all or nothing in regards to its exports. It doesn't look like you can import specific icons.
* We can use webpack stats to compare various icon package sizes (if the publisher doesn't already list it) and then pick whichever is "lightest".
* Because of the "dynamic" nature of `Icon` component we probably cannot utilize tree-shaking OOTB. With a different icon package we may be able to do away with the `Icon` component and import specific icons.

*Open Question*

* Why did we use feathericons in the first place? For the SVG output? Size? Just looking for some background.

**Comment by ericerway** [comment]
Thanks for the readout @sirugh -- @jimbo can help with the rationale and collaboration on which option to move forward with on this one.
