### ISSUE TITLE
[Improvement]: Handling images for items in the cart

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#455]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3  |
| Operating System + version  | Ubuntu 18.04  |
| node.js version (`node -v`) | 8.12.0  |
| npm version (`npm -v`)      | 6.4.1  |

## Description

Right now when user clicks on button 'Add to cart' on  product page, we save product image in local storage and display it in the product list inside mini cart panel. We never clear this images cache.

## Expected result:

Ideally, image should be a part of each item object in cart state. We should receive it from Magento when we fetch a list of cart items.

## Possible solutions:

Right now we can execute graphql query to receive images for all items in cart when we dispatch getCartDetails action after all changes in cart state.

**Comment by supernova-at** [comment]
Removing the `MM19UK` label until we can verify that this is still a valid issue.

**Comment by sirugh** [comment]
@awilcoxa this is still technically a problem -- say you are log in on your phone and add an item to cart and then move to your computer and log in. In that scenario we display a grey box in place of the actual image because there is no image url in the cache (it's only on the phone!).

I actually noted this issue in a recent PR. The solution should probably be:

1) Check cache for image and display.
2) If cached image does not exist then fetch, cache and display image from graphql
