### ISSUE TITLE
Data fetch error

### ISSUE THREAD

**Issue by m1kash** [magento-research/pwa-studio#469]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | dev-develop 2.3 |
| Operating System + version  | macOS 10.13.6 (17G65) |
| node.js version (`node -v`) | v11.1.0 |
| npm version (`npm -v`)      | 6.4.1 |

## Description

I have a data fetch error
![screenshot at nov 08 20-33-05](https://user-images.githubusercontent.com/19195462/48216395-aa348100-e395-11e8-8f97-a74a512e49ce.png)
![screenshot at nov 08 20-33-24](https://user-images.githubusercontent.com/19195462/48216396-aacd1780-e395-11e8-822a-3c09ee950986.png)

**Comment by ennostuurman** [comment]
@m1kash looks like you're running on a dev-develop 2.3 instance? I had issues with M2.3 dev branch as well . Advised M2.3 version is 2.3.0-beta32 , documents will be updated soon, see for reference https://github.com/magento-research/pwa-studio/blob/release/2.0/pwa-devdocs/src/venia-pwa-concept/setup/index.md

**Comment by m1kash** [comment]
> @m1kash looks like you're running on a dev-develop 2.3 instance? I had issues with M2.3 dev branch as well . Advised M2.3 version is 2.3.0-beta32 , documentation will be updated soon, see for reference https://github.com/magento-research/pwa-studio/blob/release/2.0/pwa-devdocs/src/venia-pwa-concept/setup/index.md

Well yeah, the issue doesn't arise anymore, but now images on the PWA environment are not displayed (even though it's OK on regular Magento). See attached images
![image](https://user-images.githubusercontent.com/19195462/49108051-3b618e00-f298-11e8-85ae-f94b4dc2070e.png)
![image](https://user-images.githubusercontent.com/19195462/49108632-b6777400-f299-11e8-9950-020cfa85f0a4.png)

**Comment by ennostuurman** [comment]
@m1kash  looks like you're using a local Magento 2.3 instance for your back-end ( http://magento-edu.local/ ). From what I see there's probably some misconfiguration on your local Magento instance / server but I can only guess. So here's some questions / remarks that might help you to solve the issue:

1) do the requested images exist on the local Magento instance?
2) are file / folder permissions right ?
3) local server is not configured correctly exposing root instead of pub only (pub/media should be media). I am not sure if this has effect on retrieval of images in PWA Studio.
4) noticing your local server runs on http instead of https
5) noticing that you Venia instance requests http instead of https images (while Venia should run on https).

**Comment by ennostuurman** [comment]
@m1kash see my reply from last week, did you manage to get PWA Studio running on your end?

**Comment by awilcoxa** [comment]
Closing as this doesn't appear to be a current issue. If this error is still occurring please re-open

**Comment by chakravarthykalyan90** [comment]
Hi @ennostuurman ,

I managed to run Venai frontend however facing the same issue.  Here are the comments to your questions. Please Help with your suggestions.

1. do the requested images exist on the local Magento instance? - Yes, Images are loading in local instance.
2. are file / folder permissions right ? - Yes
3. local server is not configured correctly exposing root instead of pub only (pub/media should be media). I am not sure if this has effect on retrieval of images in PWA Studio. - Yes pub/media is the media and the local instance is pointing to pub/index.php
3. noticing your local server runs on http instead of https - My instance is running on HTTPS
5. noticing that you Venia instance requests http instead of https images (while Venia should run on https). - Images Request URL is different for me.

![Data-fetch-error](https://user-images.githubusercontent.com/3271931/56484441-4a6a0680-64ed-11e9-917a-88406e551e72.JPG)
![image-request-URL](https://user-images.githubusercontent.com/3271931/56484444-4d64f700-64ed-11e9-9f2a-4b2a9a50cba6.JPG)
![Image-not-loading](https://user-images.githubusercontent.com/3271931/56484445-4e962400-64ed-11e9-863e-3a8cf82a743c.JPG)
