### ISSUE TITLE
 [BUG] Update Content of Checkout Receipt

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#816]
Description:
After placing an order on Venia store front, Order Number displayed on Venia store front is different than order number displayed on Admin UI.

1. Go to Venia storefront and a add product to cart.
2. Complete the order checkout process (Place the order).
3. Note the order number displayed on storefront and compare the same on Admin UI >Sales>Order

Expected behavior:
Order number should be the same.

Actual:
Order number are different.

## Proposed Solution
Given limitations of the REST API, we're not able to retrieve the External/Sequence ID for guest users w/o implementation of admin REST access functionality into UPWARD, which we'd prefer not to do. We will instead modify the content of the order receipt to instead display a more general message, which you can find mocks for in a comment below.

**Comment by dpatil-magento** [comment]
@awilcoxa is this duplicate of #841 ?

**Comment by tjwiebell** [comment]
@ericerway - Made some bad assumptions that this data was available, but it appears it is not. The REST request returns the `entity_id` instead of the external id, and there is no non-auth endpoint for retrieving order details, requires an admin token. Ideally this would be fixed when GraphQL coverage covers checkout, but we'll need to decide on an alternative solution until then.

Do you just want to remove the `Your Order # is ...` text from the receipt for now, or leave the wrong ID in place?

**Comment by supernova-at** [comment]
1. We need to remove the wrong ID and change the content of the receipt
1. Open a new ticket to the GraphQL team so that we get the correct ID

**Comment by supernova-at** [comment]
Need a design from @soumya-ashok / @awilcoxa .

**Comment by soumya-ashok** [comment]
@supernova-at Need a little more information before I can create a mockup.

**Comment by soumya-ashok** [comment]
@tjwiebell Review please

Modified mockup for the existing order details page to not show an order number - https://magento.invisionapp.com/share/S6OGPZQN4QC

New order details page mockup that is appropriate for an authenticated user - https://magento.invisionapp.com/share/MWRRJ212TF9
