### ISSUE TITLE
DISCOVERY: Identify breaking changes and impact to PWA from 2.3.1

### ISSUE THREAD

**Issue by awilcoxa** [magento-research/pwa-studio#948]
As a PWA core team, we need to understand all of the breaking items contained within the Magento 2.3.1 release which impact PWA in order to build out a plan for addressing and ensuring compatibility.

**Comment by awilcoxa** [comment]
effort is currently in progress via email thread with @zetlen

**Comment by cherdman** [comment]
From Zetlen:

https://github.com/magento/graphql-ce/pull/132 is a breaking change to the GraphQL schema. This is the small_image change we’ve already found, escalated, and discussed. It changes the small_image in ProductInterface from a string to a complex type with path and url properties. Our Venia queries expect the simple string, so they cause a type error from the API, since complex types require a subselection. To fix this, we’ll need to update every place we use the small_image property: https://github.com/magento-research/pwa-studio/search?q=small_image&unscoped_q=small_image .
 
https://github.com/magento/graphql-ce/pull/186 is a breaking change to the GraphQL schema. This changes the description and short_description fields in ProductInterface from strings to complex types with html properties. Our Venia queries expect the simple string, so they cause a type error from the API as in above. To fix this, we’ll need to update every place we use the description and short_description properties:  https://github.com/magento-research/pwa-studio/search?l=GraphQL&q=description&type=Code

**Comment by awilcoxa** [comment]
Closing as done as both issues reference above are accounted for in PR #653
