### ISSUE TITLE
<Security> "https://magento-venia.now.sh/js/"  results in errors/warning message that may disclose sensitive information.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#957]
Description:
Access "https://magento-venia.now.sh/js/"  this page shows error messages which might have sensitive data.

Steps - 
1. Access https://magento-venia.now.sh/js/ from any browser.

Expected :
Should be 404 error

Actual - 
PFA screen.

OWASP ZAP list it as Medium priority security alert. 

Screen :
![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/c6f1dd89-18b4-46b8-af34-2ca8a24b0c07)

**Comment by sirugh** [comment]
The deployment for `magento-venia` looks like it is based on whatever was deployed before the [now.sh rework](https://github.com/magento-research/pwa-studio/pull/1165).

The current develop state, https://magento-venia-develop.now.sh/js/, displays a 404 rather than the vulnerable page. So I think this is technically no longer a bug and we can probably close it when #1165 is fully released.

**Comment by dpatil-magento** [comment]
OWASP no more complaint about these kind of error on PWA develop branch. Closing this one.
